export function korpus() {
    return 'Rodinná anamnéza: Dieťa vyrastá v úplnej rodine, súrodencov nemá. Matka aj otec majú ukončené vysokoškolské vzdelanie humanitného zamerania, obaja sú zamestnaní a pracujú v štátnej správe ( v exekutíve ). Rodina žije v meste, v rodinnom dome, A.B. má samostatnú detskú izbu.\n' +
        'Matka neuvádza v rodine výskyt súvzťažných druhov ochorení alebo narušení. U otca je prí-tomné zrýchlené tempo reči ( v detstve u neho bola diagnostikovaná dyslália – rotacizmus, t.č. v norme ), iné druhy NKS sa podľa neho v rodine nevyskytli. Rodičia neuvádzajú žiadne pa-tologické faktory rodinného prostredia.\n' +
        '\n' +
        'Osobná anamnéza: Tehotenstvo prebehlo bez komplikácií, pôrod bol spontánny, fyziologic-ký, záhlavím. P. v. 3800 g, P. dĺ. 51 cm, dojčený bol do 6. mesiaca. Prekonal bežné detské ochorenia, hospitalizovaný nebol. Symptómy súvzťažných druhov NKS, prípadne iných ochorení a narušení matka neuvádza.\n' +
        '\n' +
        'Scholarita: Dieťa navštevovalo materskú školu v mieste bydliska od troch rokov. V súčasnosti navštevuje prvý ročník základnej školy v mieste bydliska. Triedny kolektív je od začiatku školskej dochádzky nezmenený, s počtom žiakov 26. Matka uvádza sporadické prob-lémy s výsmechom zo strany spolužiakov ( niekedy sa ho pýtajú „prečo kokce“ ). Triedna učiteľka je k problému dysfluencie žiaka tolerantná, podľa slov matky eliminuje slovné odpo-vede žiaka pred celou triedou, najmä v obdobiach zhoršenia plynulosti reči - na začiatku škol-ského roka ( matka po konzultácii s logopédkou CD SZU informovala o dysfluencii dieťaťa učiteľku ešte pred začatím školskej dochádzky ). A.B. je kolektívom spolužiakov síce akcep-tovaný, ale veľmi sa nepresadzuje, ani sa často verbálne neprejavuje.\n' +
        '\n' +
        'Patogenéza: Matka uvádza, že u A.B. sa prvé slová začali objavovať až okolo 3. roku života – napr. vo/voda; pi/piť. Po 4. roku dieťa postupne začalo tvoriť 2 – slovné vety. Slovná zásoba dieťaťa je nižšia, neprimeraná veku, ťažkosti sa prejavujú v pomenovaní (vo vybavení si) bežných slov, zvierat, vecí bežného použitia. Sporadicky sa v reči dieťaťa vyskytujú dys-gramatizmy a nedostatky je možné pozorovať aj v syntaktickej zložke spontánneho prehovoru. Porozumenie hovorenej reči je zachované, splní aj zložitejšiu verbálnu inštrukciu.\n' +
        '\n' +
        '     Rodičia taktiež uvádzajú, že v minulosti (približne pred 2 rokmi) s dieťaťom začali navštevo-vať logopedickú ambulanciu v mieste bydliska, kde bola kvôli dyslálii dieťaťa realizovaná korekcia sigmatizmu a rotacizmu. Nakoľko sa po dlhšom čase nedarilo tento problém odstrá-niť, bola po konziliárnom vyšetrení na pracovisku chirurgie realizovaná frenulotómia. Po tomto zákroku A.B. odmietal pokračovať v logopedickej terapii korekcie dyslálie a rodičia z týchto dôvodov terapiu prerušili. V súčasnosti pretrváva nekonštantný rotacizmus, u dieťaťa sú prítomné artikulačné deficity v oblasti špecifických asimilácií. Oromotorika je v rámci izo-lovaných pohybov v norme, deficity je možné pozorovať v motorických sekvenciách. Fone-matická diferenciácia je v norme, diskriminácia dlhej – krátkej, znelej – neznelej, mäkkej – tvrdej hlásky je A.B. izolovane rozlišovaná bez ťažkostí. Spontánny prehovor dieťaťa je v oblasti melódie a prízvuku reči charakerizovaný nepoužívaním dištinktívnych príznakov foném MJ – suspektná verbálna dyspraxia. Tempo reči je zvýšené / kolísavé, pauzy ( najmä v rámci slova ) tvorené nesprávne. Hlas je tvorený s námahou, s tvrdými hlasovými začiat-kami, prítomné je kolísanie tónovej výšky. Rezonancia je mierne zvýšená v zmysle hyperna-zality.\n' +
        '\n' +
        '     Terapia balbuties u A.B. v minulosti nebola realizovaná.\n' +
        '\n' +
        '     Prvopočiatky dysfluencie dieťaťa uvádza matka v období na konci 4. roku života, v období predškolského veku. Zajakavosť vznikala postupne, prvá ju evidovala matka. Prvými symp-tómami boli repetície kratších slov a častí slov najčastejšie na prvej slabike, najmä v situáciách, keď chcel A.B. rodičom niečo rýchlo povedať. Matka na dysfluenciu reagovala upozorňovaním aby neplynulé slovo ešte raz zopakoval, resp. aby sa poriadne nadýchol, kým začne hovoriť. Postupne sa v reči začali objavovať prolongácie (trvajúce spočiatku 1-2 sekun-dy) a prejavy nadmernej námahy (matka uvádza neprirodzené prižmurovanie očí, vraštenie čela počas prekonávania bloku spojené s dvíhaním obočia, občas už aj sprevádzané s výskytom blokov v reči). Frekvencia a stupeň symptómov sa podľa rodičov stupňovali najmä pri komunikácii s cudzími ľuďmi alebo v situáciách, keď chcel niečo rýchlo povedať alebo oznámiť (pri pozitívne aj negatívne prežívaných emóciách). Porovnanie zhoršenia resp. zlep-šenia úrovne plynulosti reči dieťaťa v školskom prostredí nevedia zhodnotiť.\n' +
        '\n' +
        '     Medzi pozitívnymi vplyvmi na fluenciu dieťaťa matka uvádza obdobie prázdnin (kontakt so starším bratrancom u starých rodičov) a víkendov (pri spoločne trávených rodinných aktivitách – spoločenské hry, prechádzky v prírode). V tomto období si všimla ústup symptómov neplynulosti.\n' +
        '\n' +
        '     Matka si v poslednom čase všimla, že s postupným stupňovaním frekvencie a stupňa symp-tómov (predlžovanie trvania prolongácií na 2-3 a viac sekúnd) sa A.B. začína vyhýbať ver-bálnej komunikácii: v rozhovoroch s rodičmi u neho prevládajú jednoslovné odpovede, je mlčanlivejší, pri prejave dysfluencie v slove je podráždený, pričom sa jeho prejavy nervozity stupňujú a prejavujú sa aj v jeho celkovom správaní k rodičom a ostatným členom zo širšieho príbuzenstva.\n' +
        '\n' +
        '     Rodičia uvádzajú výskyt spontánnych remisií, hlavne po období dlhších (letných a zimných) prázdnin. Z týchto dôvodov rodičia doposiaľ nevyhľadali logopedickú intervenciu a zvolili vyčkávací postoj, pretože predpokladali, že dysfluencia dieťaťa sa spontánne upraví. A.B. si svoju NKS uvedomuje a je vzhľadom na nadchádzajúcu terapiu motivovaný.\n' +
        '\n' +
        '     Do Centra pre dysfluencie SZU boli odporučení pedagógmi pri zápise dieťaťa do školy.\n' +
        '\n' +
        'DIAGNOSTIKA\n' +
        'Bola realizovaná podľa algoritmu štandardnej diagnostiky pracoviska Centra pre dysfluencie SZU, diagnostickým nástrojom bol Balbutiogram pre deti predškolského veku ( dieťa v tom čase ešte nemalo osvojené čítanie, september 2004 ). Objektívnu rečovú vzorku – nahrávku z domáceho ( prirodzeného ) prostredia dieťaťa sa rodičom nepodarilo z technických dôvodov získať.\n' +
        '\n' +
        'Z analýzy audiovideozáznamu 100 – slovnej rečovej vzorky spontánneho prehovoru ( úloha z Balbutiogramu ) vyplynuli nasledovné zistenia:\n' +
        'Z kvalitatívneho hľadiska klinického obrazu zajakavosti sa v oblasti dysfluencií v reči dieťaťa vyskytli repetície častí slov ( na prvej slabike slova ), repetície celých slov a slovných zvratov, interjekcie, tiché nesprávne lokalizované pauzy, opravy a prolongácie – ktoré sa vyskytovali najčastejšie.\n' +
        'V oblasti symptómov nadmernej námahy boli evidentné bloky, narušené koverbálne správanie v oblasti očí – neprirodzené prižmurovanie a dvíhanie obočia, nosa ( Fröschelsov symptóm ) a pohyby trupu dopredu pri prekonávaní dysfluencie.\n' +
        '\n' +
        'V oblasti indikátorov psychickej tenzie bolo prítomné vyhýbavé správanie ( vyhýbanie sa okluzívam ), absencia zrakového kontaktu a manipulácia s oblečením.\n' +
        'Uvedené symptómy vo všetkých troch komponentoch syndrómu balbuties potvrdzujú diagnó-zu fixovaná zajakavosť.\n' +
        '\n' +
        'TERAPIA \n' +
        'Po dohode s rodičmi dieťaťa ( o ich predstave intenzity terapie a možnostiach uvoľnenia sa zo zamestnania a pod. ) sme si určili nasledovný komplexný terapeutický program:\n' +
        '\n' +
        'aplikácia metódy FGR ( integratívny prístup ) – pracovné listy pre deti mladšieho školského veku s FZ ( s modifikáciou v etape nácviku plynulosti čítania ); v druhom polroku prvého ročníka sa prejavili ťažkosti s osvojovaním si čítania v zmysle zamieňanie hlások - napr. b - d, p - d, redukcie hlások v slovách, pridávanie hlások v rámci slov - spojené s problémami artikulačnej náročnosti slov, v ktorých sa vyskytovali zložitejšie spoluhláskové zhluky – majúce vplyv aj na fluenciu, vynechávanie dĺžňov a mäkčeňov s priemetom do grafickej stránky reči, problémy s diktátmi\n' +
        'vlastná identifikácia príznakov neplynulostí v reči ( u dieťaťa, keďže si už svoju zajakavosť uvedomuje ), vytvoriť reálnu spätnú väzbu dieťaťa na svoju fluenciu / dysfluenciu – základ pre vznik kontroly nad rečou / plynulosťou, prevetívne opatrenia  voči dysfukčnému copingu týkajúce sa percipovania problému\n' +
        'intenzívne symetrické poradenstvo pre rodičov detí s FZ ( zmena komunikačného štýlu rodičov s dieťaťom, tréning zrakového kontaktu počas komunikácie, spomalenie tempa reči zo strany otca dieťaťa, dodržiavanie komunikačných pravidiel – poskytnutie času na odpoveď, neupozorňovať na neplynulosť dieťaťa počas obdobia zhoršenia fluencie reči )\n' +
        'identifikácia príznakov zajakavosti zo strany rodičov ( pre účely osvojenia si flexibilnejšej komunikácie s dieťaťom, uvedomenie si ťažších a ľahších príznakov zajakavosti dieťaťa – pre účely prispôsobenia rodičovských výchovných opatrení, monitorovaniu/sledovaniu stavu plynulosti reči dieťaťa – registrovať zmeny v horších  a lepších obdobiach fluencie resp. dysfluencie a situácie, ktoré majú vplyv na plynulosť reči - únava, udalosti a zážitky zo školy pre účely ich prípravy na prípadné recidívy )\n' +
        'v neskorších fázach terapeutického procesu udržiavanie a event. zlepšovanie novona-dobudnutej plynulosti reči v rolových hrách, skupinová terapia na udržanie motivácie dieťaťa k terapii zajakavosti, príprava na transfer novonadobudnutej plynulosti reči a imunizácia voči obavám z verbálnej komunikácie dieťaťa v podmienkach bežného života\n' +
        'Terapeutický proces bol realizovaný v nasledovných etapách:\n' +
        '\n' +
        'týždeň pred začatím terapie bola realizovaná DG I\n' +
        'intenzívnou individuálnou formou ( 1 – krát týždenne ) počas obdobia 6 mesiacov ( po období terapie realizovaná DG II )\n' +
        'skupinovou formou ( 1 – krát za 2 – týždne ) počas obdobia 18 mesiacov ( po tomto období bola realizovaná DG III )\n' +
        'sporadicky individuálnou formou ( 1 – krát za mesiac ) počas obdobia 6 mesiacov ( po jeho ukončení sme realizovali DG IV )\n' +
        'Celkové obdobie trvania terapeutického procesu je 30 mesiacov ( t.j. 2 roky 6 mesiacov )\n' +
        '\n' +
        'KVANTITATÍVNE HODNOTENIE DYSFLUENCIÍ\n' +
        '     Z transkripcie 100 – slovnej rečovej vzorky spontánneho prehovoru ( úloha z balbutiogramu ) môžeme pozorovať v rámci DG II ( bezprostredne po terapii metódou FGR intenzívnou indi-viduálnou formou ) v porovnaní s DG I zníženie počtu prolongácii z 15 na 4, takisto nastalo zníženie počtu všetkých repetícií z 13 na 8, počet interjekcií sa znížil zo 6 na 2 a počet tichých nesprávne lokalizovaných páuz sa znížil z 3 na 2. Objavili sa však predtým sa neprejavujúce symptómy – prerušovanie slov ( 3 – krát ) a nekompletné slovné zvraty ( 3 - krát ). Opravy vzrástli z počtu 1 na 3.\n' +
        '\n' +
        '     V rámci DG III sa výskyt repetícií v porovnaní s DG II výrazne nezmenil – ich počet bol 7, avšak v porovnaní s DG I bola zmena k lepšiemu evidentnejšia. Počet prolongácií sa v porovnaní s DG II taktiež výrazne nezmenil, bol zaznamenaný z 8 na 7. Interjekcie a tiché nesprávne lokalizované pauzy sa znížili z počtu 2 na 1 v porovnaní s DG II, ale voči DG I možno pozorovať výraznejší pokles týchto symptómov t.j. z počtu 6 na 1. Nekompletné slovné zvraty a opravy sa v porovnaní s DG II znížili vo výskyte frekvencií z 3 na 2. Prerušované slová sa zvýšili z počtu 3 na 2 voči DG II.\n' +
        '\n' +
        '     V rámci DG IV sa počet repetícií voči DG III nezmenil, voči DG II sa zmenil z počtu 8 na 7 – možno konštatovať stabilizáciu tohto symptómu, avšak voči DG I je jeho zmena počtu evi-dentná – z 13 na 7. Predpokladáme, že sa zmenil charakter kvality tohto symptómu, jeho priemet možno pozorovať vo zvýšenej frekvencii počtu prerušovaných slov, nekompletných slovných zvratov a opráv. Počet prolongácií sa v DG IV voči DG III výrazne nemenil, vzrástol z počtu 3 na 4. Tu taktiež dochádza ku stabilizácii jeho výskytu v porovnaní s DG II a DG III, ale v porovnaní s DG I je jeho zmena počtu evidentná – zníženie počtu z 15 na 4. Jeho zmenu a stabilizáciu si vysvetľujeme jeho modifikáciou do iných symptómov, ktoré sa predtým v rečovom prehovore A. B. nevyskytovali.\n' +
        '\n' +
        '     Celková úroveň fluencie dieťaťa v úlohe spontánneho prehovoru v období pred začatím te-rapie ( DG I ) bola 62 %. Bezprostredne po absolvovaní intenzívnej individuálnej terapie FGR ( DG II ) vzrástla na 75%, čo predstavuje 13 % zvýšenie fluencie. Očakávali sme vyšší nárast fluencie reči, ale konštatujeme, že vzhľadom na druh zajakavosti (dysfluencia na báze NVR, ktorá vplyvom prostredia postupne prerástla do fixovanej zajakavosti) a ďalšie záťažové faktory (genetické) hodnotíme získanú úroveň fluencie za určitý (aspoň čiastočný) terape-utický úspech. Po zaradení dieťaťa do skupinovej terapie a jej absolvovaní ( DG III ) opäť vzrástla na úroveň 80 %, čo predstavuje v porovnaní s DG II len 5 %, ale v porovnaní s DG I predstavuje celkové zvýšenie fluencie 18 % nárast ( zrejme vplyvom skupinovej dynamiky, klesol počet indikátorov psychickej tenzie dieťaťa ) . Po ukončení ( DG IV ) individuálnej terapie s nižšou intenzitou stretnutí ako v prvej etape terapeutického procesu ( udržiavanie novonadobudnutej fluencie reči ) mierne vzrástla na úroveň 82 %, čo predstavuje v porovnaní s DG III len 2 % - né zvýšenie, ale v porovnaní s DG I ( pred začatím terapie ) je celkové zvýšenie fluencie reči 20 %. \n' +
        '\n' +
        '     Fluencia reči dieťa sa zlepšila aj z hľadiska poklesu prolongácií, čo predstavuje v porovnaní s DG I ( pred začatím terapie ) zmenu o 6 %. Predpokladáme, že úroveň fluencie dieťaťa sa už markantne meniť nebude (niektoré rezíduá symptómov dysfluencie budú perzistovať – repetí-cie častí slov, prerušenia a opravy ako následok získania lepšej kontroly nad rečou ).\n' +
        '\n' +
        '     Index zlepšenia mal po ukončení terapeutického procesu po DG IV hodnotu 0, 47 ( priebeh hodnôt IZ – po DG II 0,65 po DG III 0,52 ), môžeme konštatovať zlepšenie stavu plynulosti reči. .\n' +
        '\n' +
        'KVALITATÍVNE HODNOTENIE VÝSLEDKOV TERAPIE\n' +
        '     Z hľadiska klinického modelu zajakavosti sa v oblasti dysfluencií výskyt prolongácií výrazne znížil - predpokladáme, že časť z nich sa transformovala do repetícií častí slov.\n' +
        '\n' +
        '     Počet repetícií slabík na začiatku slova ( hlavne na začiatku vety ) sa výrazne nezmenil. Obja-vili sa však prerušenia uprostred slov ( na konci slov nie ) – ako dôsledok transformovania / kompenzačného mechanizmu prolongácií. Taktiež možno registrovať objavenie sa symptómov nekompletných slovných zvratov a opráv, ktoré sa predtým v rečových prehovoroch A.B. neprejavovali. Predpokladáme, že pravdepodobne ide o dôsledok zmeny charakteru kvality príznakov.\n' +
        '\n' +
        '     V oblasti nadmernej námahy postupne vymizli bloky, znížilo sa narušené koverbálne správanie zo stupňa 3 na 1, perzistuje dvíhanie čela pri prekonávaní dysfluencie.\n' +
        'V oblasti psychickej tenzie sa vyhýbavé správanie vzhľadom na obávané slová začínajúce na okluzívy zlepšilo, zotrváva však v situáciách v kontakte s cudzími ľuďmi a v niektorých situ-áciách v školskom prostredí (odporúčame psychologickú intervenciu resp. psychoterapiu). Manipulácia s oblečením a predmetmi počas komunikácie ako prejav psychickej tenzie v porovnaní pred začatím terapie a po absolvovaní terapeutického procesu skoro úplne vymiz-la, stupeň sa znížil z 3 na 1. Udržiavanie zrakového kontaktu zaznamenalo taktiež výraznú zmenu zo stupňa 3 na 1.\n' +
        '\n' +
        'ZHRNUTIE VÝSLEDKOV\n' +
        '     Z komplexného hľadiska možno konštatovať zlepšenie symptomatiky vo všetkých oblastiach klinického obrazu zajakavosti.\n' +
        '\n' +
        '     Z kvantitatívneho hľadiska klesol počet príznakov v oblasti dysfluencií – najvýraznejší pokles zaznamenali prolongácie. V oblasti nadmernej námahy sa zmirnil jej stupeň z 3 na 1. V oblasti psychickej tenzie možno taktiež konštatovať zmenu stupňa z 3 na 1.\n' +
        '\n' +
        '     Z kvalitatívneho hľadiska sa príznaky fixovanej zajakavosti u dieťaťa zmiernili, globálne hodnotenie stavu by sme mohli charakterizovať ako zlepšenie (aj z pohľadu hodnotenia dieťa-ťa a rodičov – subjektívne percipovanie stavu plynulosti reči ).\n' +
        '\n' +
        'ZÁVER\n' +
        '     Snažili sme sa naznačiť, že terapeutický proces u detí s FZ nekončí administrovaním pracov-ných listov ( po 3 - 6 mesiacoch trvania terapie zajakavosti, ale pokračuje udržiavaním novo-nadobudnutej plynulosti reči dieťaťa a jej transferom do bežného života ( do prostredia mimo logopedickej ambulancie – intenzita terapeutických stretnutí má tendenciu sa postupne znižo-vať t.j. 1- krát za 2 týždne, neskôr 1 – krát za mesiac, neskôr sa mení na katamnestické / po-stterapuetické kontroly ). Tento proces trvá približne 2 roky a samozrejme podľa potreby aj dlhšie časové obdobie v závislosti od druhu a stupňa rozvinutia syndrómu balbuties.'
}