export function korpus() {
    return 'Nadvezovanie kontaktu s dieťaťom prebiehalo spočiatku ťažšie ,dieťa bolo ostichave, neskôr sa osmelilo a spolupráca s ním bola dobrá. Diagnosticke sedenie bolo vyčlenené kontextu hrovych činnosti, prácou s obrázkovými kartami, bublifukom,artikulacnym testom a prstovymi bábikami.\n' +
        'Dieťa splnilo zadané inštrukcie a ochotne maninipuloval s bankami podľa pokynov, občas vo viacerych zadaných zadaniach inštrukcie. Ukladal ich do dlane podľa zadaných pokynov a dokázal splniť jednoduché 1-krokové inštrukcie za sebou.\n' +
        'Porozumenie dieťaťa nie je na veku primeranej úrovni-jemierne oslabené. Počas hry bolo udržiavanie a iniciáciá očného kontaktu mierne oslabené, tak isto aj ako ajstriedanie rolí na verbálnej neverbálnej úrovni.\n' +
        'Spontánna rečová produkcia je menej zrozumiteľná. Dieťa používa jednoduché viacslovné vety. Slovná zásoba je v oblasti pasívneho a aktivnehomslovnika mierne oslabená,často používa odpoved"neviem" avšak po nápovede odpoved pozná.\n' +
        '\n' +
        'Jazykový cit nie je veku primeraný,v tomto obdoby je vetná syntax a morfológia na veku neprimeranej úrovni. V reči sú časté zámeny hlások alebo ich vynechavanie. V reči sa objavujú časté dysgramatizmy. Narativa dieťa tvorí, hlavne co pozorujem pri spontánnej recovej produkcii. Fonematicka diferenciácia je na dobrej úrovni. Tempo reči je primerane, bez prvkov dysfluencii v reči.\n' +
        'V jednotlivých subjektoch správne odvodzuje žensky a mužský rod podstatných mien. Po názorovej ukážke dokáže s pomocou dospelého odvodzuje prídavné mena od podstatných mien. Primerane zvládol tvorbu minulého času primpomenivani činnosti počas dňa. Rody podstatných mien v danom subteste tvorí. Zdrobneniny slov dokáže vytvoriť pri všetkých zadaných slovách. Artikulacia dvohlasok,samohlasok a ostatných hlások(PBM,FV,TDN,ŤĎŇ,G,H,CH,J,ŠŽČ) je správne v artikulacnom teste aj spontánnej produkcii. Hláska R je vyvodena, avšak dieťa ju používa len v artikulacnom teste. Hláska L je artikulovana na nesprávnom mieste pre oslabené svalstvo jazyka. V spontánnej produkcii má dieťa tendenciu nesprávnej interdentalnej výslovnosti. Hlas je tvorený primeranou intenzitou ,čistý hlas šelestu, dýchanie je správne- s nádychom nosom.\n' +
        'Jazyk je primeranej veľkosti s mierne oslabenou motorikou. Poloha ,pohyblivosť a veľkosť pier je v norme,v kludovej tvoria pevný uzáver. Myofunkcnu poruchu nemá. Pozornosť dieťa je primeraná počas riešenia všetkých úloh.'
}